### ISSUE TITLE
Does not build: missing `Fix`.

### ISSUE THREAD

**Issue by kindaro** [JeffreyBenjaminBrown/hode#16]
When trying to build the project, I am seeing this error:

```
Hode/Rslt/Show/Util.hs:45:25: error:
    Not in scope: type constructor or class ‘Fix’
   |
45 |   :: forall att. Int -> Fix (ExprFWith att)
   |                         ^^^
```

— And many of the same further down the road.

Is this a dependency problem?

**Comment by JeffreyBenjaminBrown** [comment]
Looks like it. Are you using Stack? If so, using one of the two `stack.yaml` files in `stack-options/` should work. If you're not using Stack I'm sure building it is possible but I can't offer advice.

**Comment by kindaro** [comment]
I am using Cabal. I had to remove Stack recently because I am out of storage space and there can be only one. I am going to look into it but if you can tell me what package `Fix` is coming from it would make the task much easier for me since it would take the effort of scanning all versions of all dependencies for me to find this out.

**Comment by JeffreyBenjaminBrown** [comment]
With pleasure :) It's coming from recursion-schemes-5.1.3, which I looked up from [the package list](https://www.stackage.org/lts-16.0) for Stackage LTS 16.0. Hopefully if other compatibility problems arise they can be found there too.

Note that VTY and Brick are not included in that snapshot. The `stack.yaml` files specify which versions of them I'm using, by the commit hash I believe:

```
extra-deps:
   - brick-0.50@sha256:c06764c6471f982283d68757dbbf6ab6c75a7e86dd9ca93d3abad7e9c89b766a,14378
   - vty-5.26@sha256:7b1aeebff12d9c8ad43fe997ee0e29cd651eff2d5a0aeceeb9df2ee68efe9c53,20307
```
